name: Stable release

on:
  push:
    tags: ["v*"]

permissions:
  packages: write
  contents: read

jobs:
  parse-version:
    runs-on: ubuntu-latest
    outputs:
      build-version: ${{ steps.version.outputs.build }}
      prerelease-version: ${{ steps.version.outputs.prerelease }}
    steps:
      - name: Parse semver string
        id: version
        uses: booxmedialtd/ws-action-parse-semver@7784200024d6b3fc01253e617ec0168daf603de3
        with:
          input_string: '${{ github.ref_name }}'
          version_extractor_regex: '^v(.*)$'

  build-all:
    uses: StrikerX3/Ymir/.github/workflows/build.yaml@main
    needs: [parse-version]
    with:
      dev-build: false
      debug-symbols: false
      build-version: ${{ needs.parse-version.outputs.build-version }}
      prerelease-version: ${{ needs.parse-version.outputs.prerelease-version }}

  release:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    needs: [build-all]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Download Ymir artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          path: ymir
          pattern: ymir-*
          merge-multiple: true

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --draft \
            --latest \
            --title "Ymir ${{ github.ref_name }}" \
            ymir/*
